<?php
/**
 * integer_net Magento Module
 *
 * @category IntegerNet
 * @package IntegerNet_<Module>
 * @copyright  Copyright (c) 2012-2013 integer_net GmbH (http://www.integer-net.de/)
 * @author Viktor Franz <vf@integer-net.de>
 */

/**
 * Enter description here ...
 */
?>

<?php /** @var $this IntegerNet_Varnish_Block_Js */ ?>

<script type="text/javascript">
    var integerNetVarnish = new IntegerNetVarnish('<?php echo $this->getFetchUrl() ?>');
</script>
