<?php
/**
 * integer_net GmbH Magento Module
 *
 * @package    IntegerNet_Varnish
 * @copyright  Copyright (c) 2015 integer_net GmbH (http://www.integer-net.de/)
 * @author     integer_net GmbH <info@integer-net.de>
 * @author     Viktor Franz <vf@integer-net.de>
 */

/**
 * @var $this IntegerNet_Varnish_Block_Js
 */
?>

<script type="text/javascript">
    (function() {
        <?php if ($this->getNotCached()): ?>
        var _fetchBlocks = false;
        <?php else: ?>
        var _fetchBlocks = Mage.Cookies.get('<?php echo IntegerNet_Varnish_Model_CacheControl::FETCH_DYNAMIC_BLOCKS_COOKIE_NAME ?>');
        <?php endif; ?>

        var integerNetVarnish = new IntegerNetVarnish(_fetchBlocks);
        if (!_fetchBlocks) {
            integerNetVarnish.blocks = <?php echo $this->getDefaultBlocksJson(); ?>;
        }
    })();
</script>
