<?php
/**
 * integer_net Magento Module
 *
 * @category IntegerNet
 * @package IntegerNet_<Module>
 * @copyright  Copyright (c) 2012-2013 integer_net GmbH (http://www.integer-net.de/)
 * @author Viktor Franz <vf@integer-net.de>
 */

/**
 * Enter description here ...
 */
?>

<?php /** @var $this IntegerNet_Varnish_Block_Adminhtml_Cache_Additional */ ?>

<?php if ($this->canShowIndexButton()): ?>
<table class="form-list">
    <?php if ($this->canShowIndexButton()): ?>
        <tr>
            <td class="scope-label">
                <button onclick="setLocation('<?php echo $this->getIndexUrl() ?>')" type="button" class="scalable"><span><?php echo Mage::helper('integernet_varnish')->__('Full Page Cache Index') ?></span></button>
            </td>
            <td class="scope-label">
                <?php echo Mage::helper('integernet_varnish')->__('External varnish cache index.')?>
            </td>
        </tr>
    <?php endif; ?>
</table>
<?php endif;?>
